In [1]:
import pandas as pd
data = pd.read_csv("odev_tenis.csv")
df = data.copy()


In [2]:
df.head()

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [3]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
lego = ["windy","play"]

for i in lego:
    df[i] = le.fit_transform(df[i])

In [4]:
ohe = OneHotEncoder()
df_1 = df.iloc[:,:1]
out = ohe.fit_transform(df_1).toarray()

In [5]:
out

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [6]:
import numpy as np
out1 = pd.DataFrame(data=out,columns=["overcast","rainy","sunny"])
df1 = pd.concat([df,out1],axis=1) 
df1.drop("outlook",axis=1,inplace=True)
df1
from statsmodels import api as sm
X = df1.drop("humidity",axis=1)
y = df1[["humidity"]]
c = np.append(arr=np.ones((14,1)).astype(int),values=X,axis=1)
X_l = X.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(endog=y,exog=X_l).fit()
model.summary()

C:\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Tue, 06 Jul 2021   Prob (F-statistic):              0.661
Time:                        19:10:56   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4920      0.597      0.825      0.433      -0.884       1.868
x2            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x3            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x4            52.3891     50.214      1.043      0.327     -63.404     168.183
x5            55.6337     45.233      1.230      0.254     -48.673     159.940
x6            49.4291     48.337      1.023      0.336     -62.035     160.893
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred

array([[ 90.92694169],
       [ 69.54240608],
       [102.53382116],
       [ 86.05473611],
       [ 89.74325882]])

In [8]:
df1

temperature  humidity  windy  play  overcast  rainy  sunny
0            85        85      0     0       0.0    0.0    1.0
1            80        90      1     0       0.0    0.0    1.0
2            83        86      0     1       1.0    0.0    0.0
3            70        96      0     1       0.0    1.0    0.0
4            68        80      0     1       0.0    1.0    0.0
5            65        70      1     0       0.0    1.0    0.0
6            64        65      1     1       1.0    0.0    0.0
7            72        95      0     0       0.0    0.0    1.0
8            69        70      0     1       0.0    0.0    1.0
9            75        80      0     1       0.0    1.0    0.0
10           75        70      1     1       0.0    0.0    1.0
11           72        90      1     1       1.0    0.0    0.0
12           81        75      0     1       1.0    0.0    0.0
13           71        91      1     0       0.0    1.0    0.0

In [9]:
##backward işlemi 
c = np.append(arr=np.ones((14,1)).astype(int),values=X,axis=1)
X_l = X.iloc[:,[0,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(endog=y,exog=X_l).fit()
model.summary()

C:\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Tue, 06 Jul 2021   Prob (F-statistic):              0.546
Time:                        19:10:56   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.6484      0.506      1.282      0.232      -0.496       1.793
x2            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x3            36.6564     39.905      0.919      0.382     -53.615     126.927
x4            41.9135     36.464      1.149      0.280     -40.573     124.400
x5            35.1064     39.339      0.892      0.395     -53.884     124.097
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
x_train = x_train.drop("windy",axis=1)
x_test = x_test.drop("windy",axis=1)

In [12]:
model = lr.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred

array([[89.87120889],
       [74.14737292],
       [97.07646305],
       [82.26313541],
       [92.66809056]])

In [13]:
y_test

humidity
9         80
11        90
0         85
12        75
5         70

In [15]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
r2

-3.2447319027984127